version: v1.64.8
plugins:
  - module: 'github.com/smeshkov/golangci-lint-plugins'
    import: 'github.com/smeshkov/golangci-lint-plugins/modernfor/plugin'
    path: /Users/sergeymeshkov/src/golangci-lint-plugins
