version: v2.11.4
plugins:
  - module: 'github.com/smeshkov/golangci-lint-plugins'
    import: 'github.com/smeshkov/golangci-lint-plugins/modernfor/plugin'
    path: .
  - module: 'github.com/smeshkov/golangci-lint-plugins'
    import: 'github.com/smeshkov/golangci-lint-plugins/useany/plugin'
    path: .