version: v2.14.0
plugins:
  - module: 'github.com/smeshkov/golangci-lint-plugins'
    import: 'github.com/smeshkov/golangci-lint-plugins/modernfor/plugin'
    path: .
  - module: 'github.com/smeshkov/golangci-lint-plugins'
    import: 'github.com/smeshkov/golangci-lint-plugins/useany/plugin'
    path: .